### ISSUE TITLE
couldn't find "libavutil.so"   Error in android 10 version 

### ISSUE THREAD

**Issue by 20101994aqeel** [a914-gowtham/Android-video-trimmer#4] opened 2020-08-28 06:21 UTC
@a914-gowtham  Library is working perfect upto android 9 but when i test it in android 10 or 11 my app crash.
Error report is given below

Device: Samsung Galaxy S10 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.qboxus.musictok-TNRX9lFlXxLwdRoIlDqLqw==/base.apk"],nativeLibraryDirectories=[/data/app/com.qboxus.musictok-TNRX9lFlXxLwdRoIlDqLqw==/lib/x86, /data/app/com.qboxus.musictok-TNRX9lFlXxLwdRoIlDqLqw==/base.apk!/lib/x86, /system/lib, /system/product/lib, /system/vendor/lib]]] couldn't find "libavutil.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
	at java.lang.System.loadLibrary(System.java:1667)
	at Jni.FFmpegCmd.<clinit>(FFmpegCmd.java:18)
	at Jni.FFmpegCmd.exec(FFmpegCmd.java:77)
	at com.gowtham.library.ui.ActVideoTrimmer.validateVideo(ActVideoTrimmer.java:449)
	at com.gowtham.library.ui.ActVideoTrimmer.onOptionsItemSelected(ActVideoTrimmer.java:428)
	at android.app.Activity.onMenuItemSelected(Activity.java:4156)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27892)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by a914-gowtham** [comment] 2020-08-29 20:41
Duplicate of #3 
use implementation 'com.github.a914-gowtham:Android-video-trimmer:1.0.5'
and change TrimmerConstants to com.gowtham.library.utils.Constants

**Comment by a914-gowtham** [comment] 2020-08-29 20:59
but the problem here is the old version is larger(22mb) than latest on one(13mb)

**Closed** 2020-09-02 18:40 UTC
Labels: duplicate
