### ISSUE TITLE
in debug mode your library working awesome

### ISSUE THREAD

**Issue by sasikumarramans** [a914-gowtham/Android-video-trimmer#36] opened 2021-03-02 13:24 UTC
Below error am facing after enabling proguard 

java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to android.widget.CompoundButton$SavedState   proguard issue

Please give me the suggestion to this

**Comment by a914-gowtham** [comment] 2021-03-02 13:34
Can you share the full error log

**Comment by sasikumarramans** [comment] 2021-03-03 03:13
Yes I have added proguard rules

java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to android.widget.CompoundButton$SavedState
        at android.widget.CompoundButton.onRestoreInstanceState(CompoundButton.java:661)
        at android.view.View.dispatchRestoreInstanceState(View.java:21574)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4699)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4699)
        at android.view.View.restoreHierarchyState(View.java:21552)
        at androidx.fragment.app.Fragment.restoreViewState(:573)
        at androidx.fragment.app.FragmentStateManager.restoreViewState(:356)
        at androidx.fragment.app.FragmentManager.moveToState(:1189)
        at androidx.fragment.app.FragmentManager.moveToState(:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(:1434)
        at androidx.fragment.app.FragmentManager.moveToState(:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(:2625)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(:2577)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(:247)
        at androidx.fragment.app.FragmentActivity.onStart(:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(:210)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
        at android.app.Activity.performStart(Activity.java:7986)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3677)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by a914-gowtham** [comment] 2021-03-03 06:59
This error happens if we have used the same id for multiple views.  share the reproducing steps so that I can try to find out the issue

**Comment by sasikumarramans** [comment] 2021-03-03 07:11
1. Just enable the proguard and add your proguard rules
2. then select one video and do some trim
3. then finally click the save button on top then you will get this issue

**Comment by a914-gowtham** [comment] 2021-03-03 08:21
Thanks, I will try to reproduce the issue here.

**Comment by a914-gowtham** [comment] 2021-03-15 18:08
Duplicate of #35

**Closed** 2021-03-15 18:08 UTC
Labels: bug
